sudo: false
language: php
php:
  - '5.6'
env:
  - noninteractive=true
before_install:
  - composer self-update
  - nvm install stable
  - nvm use stable
  - npm install -g grunt-cli
  - npm --version
  - node --version
install:
  - ./src/lib/pre-install
  - npm install
script:
  - npm test
